const serviceList = {
  postVersion: '/api/version',
  postLogin: '/api/user/login/v2',
  getCheckPolicies: '/api/user',
  getPrivacyPolicy: '/api/servicePolicy/privacyPolicy',
  putPrivacyAccepted: '/api/user',
  getPermissions: '/api/user/permissions',
  getProfiles: '/api/resident/adminResidents',
  getResidentInfo: '/api/resident/downloadServer',
  getPrototypes: '/api/prototype/resident',
  getPdf: '/api/prototype/getFile',
  postHouseFront: '/api/house/frente',
  postSet: '/api/house/conjunto',
  getVolumeProjectFilter: '/api/resident/downloadServer',
  postVolumeFrontFilter: '/api/estimate/frontCollection',
  postVolumeVendors: '/api/estimate/getContractVendor',
  postVolumeDataGreed: '/api/urbanizationEstimate/checkUrbEstimate',
  putUploadDocument: '/api/urbanizationEstimate/saveFile',
  postGetMails: '/api/urbanizationEstimate/getMails',
  postGetFilters: '/api/urbanizationEstimate/getResidentsFilters',
  postCreateEstimate: '/api/urbanizationEstimate/createUrbEstimate',
  postDiscardModal: '/api/urbanizationEstimate/discardModal',
  getSetNotification: '/api/resident/setNotification/',

  // Concrete Program
  getConcreteProgramsProjects: '/api/con/filter/resident/proyects',
  postConcreteProgramFronts: '/api/con/filter/resident/fronts',
  postConcreteProgramCollections: '/api/con/filter/resident/collections',
  getPurchaseOrders: '/api/con/purchaseOrders/resident',
  getUserProfile: '/api/con/profile/resident',
  putUpdatePhone: '/api/con/profile/resident',
  getAllCatalogs: '/api/con/mobile/concrete/all',
  putConcreteCart: '/api/con/concrete/program',
  getConcreteProgramOrders: '/api/con/concrete/program',
  getProgramDetails: '/api/con/concrete/program/detail',
  deleteConcreteProgram: '/api/con/concrete/program',
};

export default serviceList;
